### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference

### ISSUE THREAD

**Issue by adamvarhegyi** [ringcaptcha/ringcaptcha-android#1]
So after i call:

```
   RingcaptchaApplication.onboard(getApplicationContext(), "my_app_key_here", "my_secret_key_here", new RingcaptchaApplicationHandler() {
                @Override
                public void onSuccess(RingcaptchaVerification ringcaptchaVerification) {
                }
                @Override
                public void onCancel() {
                }
            });
```

I got **this exception:**

```
11-13 11:44:53.484: E/AndroidRuntime(2192): Process: com.illion.dotodo.application.sender, PID: 2192
11-13 11:44:53.484: E/AndroidRuntime(2192): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.illion.dotodo.application.sender/com.thrivecom.ringcaptcha.OnboardActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.app.ActivityThread.-wrap11(ActivityThread.java)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.os.Handler.dispatchMessage(Handler.java:102)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.os.Looper.loop(Looper.java:148)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.app.ActivityThread.main(ActivityThread.java:5417)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at java.lang.reflect.Method.invoke(Native Method)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
11-13 11:44:53.484: E/AndroidRuntime(2192): Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
11-13 11:44:53.484: E/AndroidRuntime(2192):     at com.thrivecom.ringcaptcha.BaseActivity.onCreate(BaseActivity.java:48)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at com.thrivecom.ringcaptcha.OnboardActivity.onCreate(OnboardActivity.java:53)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.app.Activity.performCreate(Activity.java:6237)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
11-13 11:44:53.484: E/AndroidRuntime(2192):     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
```

By the way, your documentation is **outdated:**

It says in docs (https://my.ringcaptcha.com/docs/android): 

"On your initial Activity, in the method hooked to the user event add the following line of code."

```
RingcaptchaApplication.onboard(getApplicationContext(),"{{ app_key }}", "{{ secret_key }}", new RingcaptchaHandler() {
  @Override
  public void onSuccess(RingcaptchaVerification o) {
      //Verification successful
  }
  @Override
  public void onCancel(RingcaptchaVerification o) {
      //Decide what do do if user cancelled operation
  }   
});
```

  But there are only these onboard functions **with different signatures:**

```
onboard(Context context, String appKey, String secretKey, RingcaptchaApplicationHandler ringah);
onboard(Context context, String appKey, String secretKey, String pin, RingcaptchaApplicationHandler ringah);
```

  **RingcaptchaApplicationHandler != RingcaptchaHandler**

Also the version **in doc** says

 compile 'com.thrivecom:ringcaptcha:**1.0.7**@aar'

 the version **in github** says

compile 'com.thrivecom:ringcaptcha:**1.0.8**@aar'

I have tried Cognalys call verification but their system got errors.
I would really like to migrate to ringcaptcha if it is working well.

Please help if you can.

**Comment by vrunoa** [comment]
@adamvarhegyi have you add:
`compile 'com.android.support:appcompat-v7:21.0.3'` 
to your gradle dependencies ?

**Comment by adamvarhegyi** [comment]
I have

 compile 'com.android.support:appcompat-v7:23.+'

**Comment by vrunoa** [comment]
@adamvarhegyi can you change it to `compile 'com.android.support:appcompat-v7:21.0.3'` to see if there's a compatibility problem ? 
Also, is the activity where you're calling ringcaptcha API extending from `ActionBarActivity` ?

Do you have any code online we can review to help you?

**Comment by dilipappectual** [comment]
Not Helped Any Solutions

**Comment by vrunoa** [comment]
What is your `<application android:theme="@style/AppTheme"` extending from ? Does it start working if you change it to the one used in the [example](https://github.com/ringcaptcha/ringcaptcha-android/blob/master/Example/app/src/main/res/values/styles.xml)

**Comment by dilipappectual** [comment]
for parent="Theme.AppCompat.Light.NoActionBar" its not working for me

**Comment by vrunoa** [comment]
Can you try with; Theme.AppCompat.Light.DarkActionBar and check if works?

**Comment by dilipappectual** [comment]
No works for Themes containing  
 **windowActionBar** to **false** and add **windowNoTitle** as well and set it to **true**
Error : 

/com.thrivecom.ringcaptcha.OnboardActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference

Solution :

Problem still persist if i have set getSupportActionBar().setDisplayHomeAsUpEnabled(false);

Please check and get back to me. thanks in advance

**Comment by dilipappectual** [comment]
FATAL EXCEPTION: main
                                                 Process:  PID: 4813
                                                 java.lang.RuntimeException: Unable to start activity ComponentInfo{com.thrivecom.ringcaptcha.OnboardActivity}: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151)
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
                                                     at android.os.Handler.dispatchMessage(Handler.java:102)
                                                     at android.os.Looper.loop(Looper.java:135)
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                     at java.lang.reflect.Method.invoke(Native Method)
                                                     at java.lang.reflect.Method.invoke(Method.java:372)
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
                                                  Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void android.support.v7.app.ActionBar.setDisplayHomeAsUpEnabled(boolean)' on a null object reference
                                                     at com.thrivecom.ringcaptcha.BaseActivity.onCreate(BaseActivity.java:48)
                                                     at com.thrivecom.ringcaptcha.OnboardActivity.onCreate(OnboardActivity.java:53)
                                                     at android.app.Activity.performCreate(Activity.java:5990)
                                                     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
                                                     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
                                                     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387) 
                                                     at android.app.ActivityThread.access$800(ActivityThread.java:151) 
                                                     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303) 
                                                     at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                     at android.os.Looper.loop(Looper.java:135) 
                                                     at android.app.ActivityThread.main(ActivityThread.java:5254) 
                                                     at java.lang.reflect.Method.invoke(Native Method) 
                                                     at java.lang.reflect.Method.invoke(Method.java:372) 
                                                     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903) 
                                                     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

Sorry not helped me .

**Comment by dilipappectual** [comment]
Can i have access to view your com.thrivecom.ringcaptcha.OnboardActivity.java files

**Comment by vrunoa** [comment]
Hey @dilipappectual i'll try to create a simple app with the "Theme.AppCompat.Light.NoActionBar" theme, and let you know if it works. I don't longer have access to Ringcaptcha repo, i'm just trying to help

**Comment by mityao** [comment]
I may have the same problem, did you find out the solution finally?

**Comment by haris15** [comment]
i have face same problem do you find any solution for that ?

**Comment by bhavincb** [comment]
any updates?

**Comment by Nounours39** [comment]
lol

**Comment by iftyfr** [comment]
???

**Comment by SibinAntony** [comment]
setSupportActionBar(toolbar);
try this

**Comment by purisahib** [comment]
private void UpdateTitle() {
        if (getActivity() instanceof AppCompatActivity){
            actionBar=((AppCompatActivity)getActivity()).getSupportActionBar();
            if (actionBar!=null) actionBar.setTitle(R.string.sub_title);
        }
    }

**Comment by purisahib** [comment]
private void loadRecords() {
        AdapterRecord adapterRecord= new AdapterRecord(getContext(),
                dbHelper.getAllRecords(Constants.C_ADDED_TIMESTAMP + " DESC"));

        recordsRv.setAdapter(adapterRecord);

        //set num of records
        //((AppCompatActivity) getActivity()).getSupportActionBar().
        //actionBar.setSubtitle("Total: "+dbHelper.getRecordsCount());
        actionBar=((AppCompatActivity)getActivity()).getSupportActionBar();
        if (actionBar!=null)actionBar.setSubtitle("Total: "+dbHelper.getRecordsCount());
    }
