### ISSUE TITLE
crash on android 7.0 (nougat)

### ISSUE THREAD

**Issue by haris15** [ringcaptcha/ringcaptcha-android#7]
in android nougat my app is crash see a log

-10798/com.cognovi.EquilibriumFX W/System.err: org.xml.sax.SAXParseException: name expected (position:START_TAG <Note content='This list is just for user reference. CountryCodePicker picks country list from getMasterCountries(), a static method of Country class'>@3:155 in java.io.InputStreamReader@8cc0ec8) 
02-19 16:45:21.172 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
02-19 16:45:21.172 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:132)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at com.thrivecom.ringcaptcha.widget.parser.CountriesParser.parse(CountriesParser.java:38)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at com.thrivecom.ringcaptcha.RingcaptchaApplication.init(RingcaptchaApplication.java:169)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at com.thrivecom.ringcaptcha.RingcaptchaApplication.onboard(RingcaptchaApplication.java:261)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at com.cognovi.EquilibriumFX.fragments.SignUpFragment.verifiedUser(SignUpFragment.java:348)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at com.cognovi.EquilibriumFX.fragments.SignUpFragment.access$100(SignUpFragment.java:55)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at com.cognovi.EquilibriumFX.fragments.SignUpFragment$checkUserExistOrNot.onPostExecute(SignUpFragment.java:270)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at com.cognovi.EquilibriumFX.fragments.SignUpFragment$checkUserExistOrNot.onPostExecute(SignUpFragment.java:204)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:660)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at android.os.AsyncTask.-wrap1(AsyncTask.java)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:677)
02-19 16:45:21.173 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
02-19 16:45:21.174 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at android.os.Looper.loop(Looper.java:154)
02-19 16:45:21.174 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6077)
02-19 16:45:21.174 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
02-19 16:45:21.174 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
02-19 16:45:21.174 10798-10798/com.cognovi.EquilibriumFX W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

**Comment by haris15** [comment]
please help to solve this issue

**Comment by nethsix** [comment]
Hello @haris15 
Thank you for reporting the issue!
We will look at it.
Do you mind sharing with us:
* How did you find RingCaptcha?
* What are you using RingCaptcha for?
* How many users do you have currently? Or how many users you will have in 3 months time?

**Comment by nethsix** [comment]
@haris15 Do you mind showing a snippet of code where the app is crashing so that we can understand what was the code doing when it crashed, and the parameters passed to the SDK/function?

**Comment by haris15** [comment]
Hello Neth

Thank you for quick respose.

**Comment by haris15** [comment]
Hello Neth
Thank you for quick response
this is snippet of Ring captcha code where my app is crash

RingcaptchaApplication.onboard(getActivity().getApplicationContext(),
"APPKEY", "SECRETKEY", new RingcaptchaApplicationHandler() {
    @Override
    public void onSuccess(RingcaptchaVerification ringcaptchaVerification) {
        //call registerUser() after verification done
        registerUser(edtFirstName.getText().toString(),
edtLastName.getText().toString(),
                edtEmail.getText().toString(), phoneNumber,
edtUsername.getText().toString(),
                edtPassword.getText().toString());
    }

    @Override
    public void onCancel() {

        sessionManager.showSnackBar("Verification failed");
    }
});


please give me solution for this issue.


Thanks

Haris

**Comment by haris15** [comment]
do you find any solution for this issue ?

**Comment by haris15** [comment]
hi neth

**Comment by haris15** [comment]
hi neth

this is an answer of your questions

1) i have find Ring Captcha from internet
2) i am using Ring Captcha for user authentication
3) i will have 100 to 500 users in 3 months time

**Comment by nethsix** [comment]
Hey @haris15 
We're still looking into this issue. we should have update for you latest by early next week.

**Comment by haris15** [comment]
please find solution for that issue

this is a log that may be help you

org.xml.sax.SAXParseException: name expected (position:START_TAG <Note
content='This list is just for user reference. CountryCodePicker picks
country list from getMasterCountries(), a static method of Country
class'>@3:155 in java.io.InputStreamReader@23a0376)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at
org.apache.harmony.xml.parsers.DocumentBuilderImpl.parse(DocumentBuilderImpl.java:146)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at javax.xml.parsers.DocumentBuilder.parse(DocumentBuilder.java:132)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at
com.thrivecom.ringcaptcha.widget.parser.CountriesParser.parse(CountriesParser.java:38)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at
com.thrivecom.ringcaptcha.RingcaptchaApplication.init(RingcaptchaApplication.java:169)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at
com.thrivecom.ringcaptcha.RingcaptchaApplication.onboard(RingcaptchaApplication.java:261)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at
com.cognovi.EquilibriumFX.fragments.SignUpFragment.verifiedUser(SignUpFragment.java:205)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at
com.cognovi.EquilibriumFX.fragments.SignUpFragment.access$500(SignUpFragment.java:55)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at
com.cognovi.EquilibriumFX.fragments.SignUpFragment$checkUserExistOrNot.onPostExecute(SignUpFragment.java:385)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at
com.cognovi.EquilibriumFX.fragments.SignUpFragment$checkUserExistOrNot.onPostExecute(SignUpFragment.java:319)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at android.os.AsyncTask.finish(AsyncTask.java:636)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at android.os.AsyncTask.access$500(AsyncTask.java:177)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at android.os.Handler.dispatchMessage(Handler.java:102)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at android.os.Looper.loop(Looper.java:135)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at android.app.ActivityThread.main(ActivityThread.java:5254)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at java.lang.reflect.Method.invoke(Native Method)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at java.lang.reflect.Method.invoke(Method.java:372)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
02-22 18:15:18.390 29416-29416/com.cognovi.EquilibriumFX W/System.err:
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
02-22 18:15:18.394 29416-29416/com.cognovi.EquilibriumFX E/AndroidRuntime:
FATAL EXCEPTION: main

 Process: com.cognovi.EquilibriumFX, PID: 29416

 java.lang.IndexOutOfBoundsException: Invalid index 0, size is 0

   at java.util.ArrayList.throwIndexOutOfBoundsException(ArrayList.java:255)

   at java.util.ArrayList.get(ArrayList.java:308)

   at
com.thrivecom.ringcaptcha.widget.model.Countries.getItem(Countries.java:75)

   at
com.thrivecom.ringcaptcha.RingcaptchaApplication.init(RingcaptchaApplication.java:189)

   at
com.thrivecom.ringcaptcha.RingcaptchaApplication.onboard(RingcaptchaApplication.java:261)

   at
com.cognovi.EquilibriumFX.fragments.SignUpFragment.verifiedUser(SignUpFragment.java:205)

   at
com.cognovi.EquilibriumFX.fragments.SignUpFragment.access$500(SignUpFragment.java:55)

   at
com.cognovi.EquilibriumFX.fragments.SignUpFragment$checkUserExistOrNot.onPostExecute(SignUpFragment.java:385)

   at
com.cognovi.EquilibriumFX.fragments.SignUpFragment$checkUserExistOrNot.onPostExecute(SignUpFragment.java:319)

   at android.os.AsyncTask.finish(AsyncTask.java:636)

   at android.os.AsyncTask.access$500(AsyncTask.java:177)

   at android.os.AsyncTask$InternalHandler.handleMessage(AsyncTask.java:653)

   at android.os.Handler.dispatchMessage(Handler.java:102)

   at android.os.Looper.loop(Looper.java:135)

   at android.app.ActivityThread.main(ActivityThread.java:5254)

   at java.lang.reflect.Method.invoke(Native Method)

   at java.lang.reflect.Method.invoke(Method.java:372)

   at
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)

   at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by ghost** [comment]
Hello @haris15 
At the moment I can't reproduce this error on my mobile phone as well as on emulators.
It would be great and very helpful for us if you could perform the following actions:
1. Provide info related to your device model and the ROM it is running on. Please, specify if it's some custom ROM.
2. Specify compileSdkVersion, targetSdkVersion and buildToolsVersion.
3. Check if the application is running correctly on other devices.
4. Check if this code is working in the pure application. 
I mean check if it is working in such case:
```java
import com.thrivecom.ringcaptcha.RingcaptchaApplication;
import com.thrivecom.ringcaptcha.RingcaptchaApplicationHandler;
import com.thrivecom.ringcaptcha.RingcaptchaVerification;

public class MainActivity extends Activity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        RingcaptchaApplication.onboard(getApplicationContext(),
                "APP_KEY", "SECRET_KEY", new RingcaptchaApplicationHandler() {
                    @Override
                    public void onSuccess(RingcaptchaVerification ringcaptchaVerification) {
                        Toast.makeText(MainActivity.this.getApplicationContext(), "Success", Toast.LENGTH_LONG).show();
                    }

                    @Override
                    public void onCancel() {
                        Toast.makeText(MainActivity.this.getApplicationContext(), "Error", Toast.LENGTH_LONG).show();
                    }
                });
    }
}
```

**Comment by haris15** [comment]
hi @OlehMo 

i have checked my code in most of all devices in android 4.0 to android 7.1 its crashed in all devices

my compileSdkVersionis 23 and targetSdkVersion is 23

i have mode demo in this i have used only ringcaptcha onboard code and its working perfectly 
same code i have used in my application but its crashed and give above error that i have mention

**Comment by nethsix** [comment]
@haris15 Can you help us check if item 4 (the code @OlehMo provided) is working correctly on one of your crashed devices? I know it will take some of your time, but if it that works, you can try moving parts of your code into @OlehMo 's base code to see if the crash happens.

At the moment as we cannot replicate the crash on our side, we will need your help to identify the part of your code that is causing the crash.

**Comment by haris15** [comment]
@nethsix the code @OlehMo provided is same code that i have used in my application.
its working if i create a demo application in which only ring captcha code is written in Oncreate method

but problem is that its not working on my current application

**Comment by ghost** [comment]
@haris15
Do you use Gradle dependency to include the Ringcaptcha SDK into your application or download **ringcaptcha.jar** from this repository?

**Comment by haris15** [comment]
yes i have use Gradle dependency to include the Ringcaptcha SDK
